### ISSUE TITLE
Don't use busybox for data-only images

### ISSUE THREAD

**Issue by derimagia** [geerlingguy/docker-examples#2]
Saw the repo and am interested in where you take this. Docker is really neat We met at Drupalcon at the sprints if you remember at all and had a short conversation on it.

I'd recommend taking a look at http://container42.com/2014/11/18/data-only-container-madness/
Pretty much it's just a waste of data since you can use a container you already have for it

**Comment by geerlingguy** [comment]
Thanks! It looks like in the time since I last poked and prodded Docker seriously (pre-1.10), data containers have been quite marginalized... and `volume`s work much more simply. See, for reference:
- https://github.com/docker/docker/issues/17798

**Comment by derimagia** [comment]
Yeah it did come a long way. I had a few issues with them when they came out a few months ago, volumes used to be mounted as root as well but it looks like that was fixed recently. I also had some similar issue issues with: https://github.com/docker/docker/issues/19990. I didn't mess with the local_persist plugin yet since I didn't want to use a plugin but I may try it out and I don't think it's what I want. I need to new updates to volumes that came out in the last version.

At any rate I do recommend using named volumes though at the very least or else you get a lot of volumes adding up.

**Comment by geerlingguy** [comment]
> At any rate I do recommend using named volumes though at the very least or else you get a lot of volumes adding up.

Haha, yes, true.

I'm hopefully going to explore volumes a bit more in-depth as I get into more involved examples. Especially when I work on the 'how do we work around the insane slowness of osxfs?' problem.

**Comment by derimagia** [comment]
[Here's a good comment on the main post to read about osxfs.](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/158?u=derimagia)

In the thread [docker_sync](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/122?u=derimagia) was also made but it still has you run something on the host machine... 

[The idea I have is mentioned here](https://forums.docker.com/t/file-access-in-mounted-volumes-extremely-slow-cpu-bound/8076/130?u=derimagia). Essentially I would make a union or syncthing 2-way sync container that syncs directories in the container - then have it mount to one of those directories using osxfs. Theoretically this should allow for file events but I haven't done too much testing yet.

In terms of other references kalabox is one I use sometimes - it uses syncthing internally but I have some gripes with some of the things it does. http://docker4drupal.org came out recently and it does everything pretty well. Here is my personal project but it has some issues that I need time to fix: https://github.com/derimagia/docker-drupal. I have separate nginx/php/mariadb/mailgun/redis containers with alpine linux as much as I can use it. There are a few things I need to fix with it and update but it's another reference. I've been mainly waiting for this osxfs fixes but I may just make a docker-sync with my ideas above when I have time

I'd be happy to help out if you decide to move forward with a project at some point. One of my end goals is for me to be able to run a command to pull down a site using drush/terminus/etc and spin up a docker instance as quickly as possible.

**Comment by geerlingguy** [comment]
@derimagia - Great references, thanks!

No matter what, I'm interested in looking into many of the different options out there, and I don't think Drupal VM will be moving directly into the same kind of setup as Kalabox or Docker4Drupal, but I would like to keep working on solutions for 'local Drupal development' that make lives better for everyone, regardless of the underlying tech.

In the Vagrant/VirtualBox world, there are a ton of different options, many that focus on one or two specific areas, and I think the same will happen with Docker and the surrounding ecosystem over the next few years.

**Comment by derimagia** [comment]
That is what I figured you would do, I don't think it is a replacement for
something like drupalvm.  Will be curious to what can be done since it
seems more and more people are trying to make cool things in rocker for
development.  Excited..  Barring the volume syncing issues...
